### ISSUE TITLE
(today task )to promes  Qty (not reserved )= onhand Qty on Product  -  the Reserved Qty

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/qaserlibya#17]
![Screenshot from 2020-02-18 01-14-34](https://user-images.githubusercontent.com/27553992/74709020-20a46d80-51ec-11ea-9e96-34aee1926167.p

**Comment by NirajPajwani** [comment]
Done

**Comment by NirajPajwani** [comment]
Done
