### ISSUE TITLE
""this day task""  make avaiable to  change  Source Location & Operation Type on 

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/qaserlibya#19]
![WH34_OUT_00004 - Osoul](https://user-images.githubusercontent.com/27553992/74855583-e1bb0880-530e-11ea-9b32-08fb5f6cdcb9.gif)

**Comment by NirajPajwani** [comment]
Let me know when I can start to work on this enhancement.

**Comment by NirajPajwani** [comment]
Done.

There is a button named "Change Operation" only visible in Waiting and Ready state will help to change the operation type, source location, and destination location.
