### ISSUE TITLE
sale auto work flow

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/qaserlibya#23]
after validation, the sale order
it triggers a popup window  for direct selecting a payment journal  &and for set  real payment amount 
with  confirm button  

if a payment equal to the total amount   the   delivery order will be visible  at stock.picking&view_type=lis
if  not  will be  invisible   

an important note is  :   the  auto creating and posting  the custome invoice will be done  before the 
riggers a popup window

**Comment by NirajPajwani** [comment]
Done
