### ISSUE TITLE
You cannot delete an entry which has been posted once.

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/qaserlibya#8]
![Screenshot from 2020-02-10 07-36-46](https://user-images.githubusercontent.com/27553992/74150549-268cc400-4bd8-11ea-8085-e37ab8d21893.png)

i want be able to delete any invoice   with  status  is   canceled

hint  : try make   the fiedl   =  name     of
    acount.move   editable

**Comment by NirajPajwani** [comment]
We can delete using the "Force Delete" button after posted the invoice.
