### ISSUE TITLE
Sale Exception Rules

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/qaserlibya#9]
Not Enough Virtual Stock

Rule Group | Sale
Apply on | Sale order line

Python Code | if sale_line.product_id and sale_line.product_id.type == 'product' and sale_line.product_id.with_context(warehouse=sale_line.order_id.warehouse_id.id).virtual_available < sale_line.product_uom_qty:     failed=True
-- | --

**Comment by abudulalibayo** [comment]
Exception Rules

**Comment by NirajPajwani** [comment]
Done
